### ISSUE TITLE
Android: SocketException error on write()

### ISSUE THREAD

**Issue by Pinwheeler** [Rapsssito/react-native-tcp-socket#31]
## Description
Reproduction unclear- it appears to happen the first(?) time a socket connection is attempted. This does not appear to happen on iOS. I'll keep investigating and see if I can get more specifics, better repro, or create an isolated test app.

## Steps to reproduce
1. Attempt to connect to socket port on android
2. See this error pop up
3. Inbound socket traffic does not show up (outbound appears to work correctly)

**Screenshots**
<img width="340" alt="Screen Shot 2020-02-27 at 9 26 11 PM" src="https://user-images.githubusercontent.com/4139124/75578053-02264980-5a18-11ea-80fd-c2a504d0534c.png">

## Relevant information
|             |     |
| ----------- | --- |
| OS | Android   |
| react-native |  0.61.5  |
| react-native-tcp-socket  | 3.2.8   |

**Comment by Pinwheeler** [comment]
The reproduction seems to be non-deterministic in my app- this happens, but only occasionally. I'll keep digging.

**Comment by Rapsssito** [comment]
Could you provide your socket connection options, please?

**Comment by Pinwheeler** [comment]
```
import TcpSocket from 'react-native-tcp-socket'
this.client = TcpSocket.createConnection({port, host})
```
port: 9876 host: 167.172.200.249

**Comment by Pinwheeler** [comment]
It looks like this could be something where the server is failing to connect and the java is throwing an error. It looks, however, like the library is not able to call the `onError` callback because it's an exception of an unexpected kind???

I can build the app to handle the connection failure if the error gets propagated up in to javascript.

**Comment by Rapsssito** [comment]
It looks like an error converting your JS arguments to Java types. Could you provide the error logs from your Android device?

**Comment by Pinwheeler** [comment]
I suspect it might be something different, but if you have a lead- that's great. Here's the android logs obtained from Android Studio LogCat. If you know of a different/better place to get them let me know

```
2020-02-28 12:56:10.919 3355-3983/dev.plenti.plenti W/v.plenti.plent: Accessing hidden method Lsun/misc/Unsafe;->putObject(Ljava/lang/Object;JLjava/lang/Object;)V (greylist, linking, allowed)
2020-02-28 12:56:10.919 3355-3983/dev.plenti.plenti W/v.plenti.plent: Accessing hidden method Lsun/misc/Unsafe;->putLong(Ljava/lang/Object;JJ)V (greylist, linking, allowed)
2020-02-28 12:56:10.923 3355-3986/dev.plenti.plenti W/v.plenti.plent: Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
2020-02-28 12:56:15.855 3355-3964/dev.plenti.plenti I/ReactNativeJS: SocketClient:: port: 9876 host: 167.172.200.249
2020-02-28 12:56:15.864 3355-3964/dev.plenti.plenti W/ReactNativeJS: We found non-serializable values in the navigation state, which can break usage such as persisting and restoring state. This might happen if you passed non-serializable values such as function, class instances etc. in params. If you need to use components with callbacks in your options, you can use 'navigation.setOptions' instead. See https://reactnavigation.org/docs/en/troubleshooting.html#i-get-the-warning-we-found-non-serializable-values-in-the-navigation-state for more details.
2020-02-28 12:56:15.865 3355-4021/dev.plenti.plenti E/unknown:ReactNative: Exception in native call
    java.lang.RuntimeException: Cannot convert argument of type class java.net.SocketException
        at com.facebook.react.bridge.Arguments.fromJavaArgs(Arguments.java:181)
        at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:30)
        at com.asterinet.react.tcpsocket.TcpSocketModule$3.doInBackgroundGuarded(TcpSocketModule.java:157)
        at com.asterinet.react.tcpsocket.TcpSocketModule$3.doInBackgroundGuarded(TcpSocketModule.java:146)
        at com.facebook.react.bridge.GuardedAsyncTask.doInBackground(GuardedAsyncTask.java:35)
        at com.facebook.react.bridge.GuardedAsyncTask.doInBackground(GuardedAsyncTask.java:19)
        at android.os.AsyncTask$3.call(AsyncTask.java:378)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
2020-02-28 12:56:15.926 3355-3355/dev.plenti.plenti W/v.plenti.plent: Accessing hidden method Landroid/graphics/FontFamily;-><init>()V (greylist, reflection, allowed)
```

**Comment by Pinwheeler** [comment]
The block that it's calling out
```
                try {
                    socketClient.write(Base64.decode(base64String, Base64.NO_WRAP));
                } catch (IOException e) {
                    if (callback != null) {
                        callback.invoke(e);
                        return;
                    }
                }
```

is catching an `IOException`. Would that catch `SocketException` objects as well?

**Comment by Rapsssito** [comment]
I'll investigate. You'll get a response in 10 hours, sorry for the delay.

**Comment by Pinwheeler** [comment]
No worries- I attached a debugger and was able to see more details about the error. I'm now seeing that it is this `java.net.SocketException: Socket is not connected` -- it's possible I have some kind of timing issue in my app.

**Comment by Rapsssito** [comment]
Does this happen when you write to the socket? Could you provide the details of what you are writing?

**Comment by Pinwheeler** [comment]
So here's the logs that I'm getting.
```
 LOG  SocketClient:: port: 9876 host: 167.172.200.249
 LOG  1%%2%%3%%2020-02-28T14:26:56.279-0800%%handshake
```

that's produced by my SocketClient file

```javascript
import TcpSocket from 'react-native-tcp-socket'

export default class SocketClient {
  static create(
    port: number,
    host: string,
    listenCallback: (line: string) => void,
    errorCallback: (error: any) => void,
  ) {
    return new SocketClient(port, host, listenCallback, errorCallback)
  }

  private client: any

  constructor(
    port: number,
    host: string,
    listenCallback: (line: string) => void,
    errorCallback: (error: any) => void,
  ) {
    try {
      if (host === '127.0.0.1') {
        this.client = TcpSocket.createConnection({
          port,
          host,
          localAddress: '127.0.0.1',
        })
      } else {
        console.log(`SocketClient:: port: ${port} host: ${host}`)
        this.client = TcpSocket.createConnection({port, host})
      }
      this.client.on('data', data => {
        listenCallback(data.toString())
      })
      this.client.on('error', error => {
        errorCallback(error)
      })
    } catch (error) {
      console.error('SocketClient -- Error', error)
    }
  }

  sendLine(line: string) {
    console.log(line)
    this.client.write(`${line}\r\n`)
  }
}
```

I'm thinking that this is a timing issue on my end- that it's connecting and not waiting for the connection to come back as established before trying to send the "handshake" line. Probably not a bug on your end. Potentially it might be nice to surface the error in a friendlier way, but I actually am not thinking this is your issue now.

**Comment by Pinwheeler** [comment]
aha! Your types update suggests there's a callback method for when the connection is established! Bravo! I'll just use that. Sorry for any unnecessary concern I might have caused. Feel free to close or keep open if you want to try to gold-plate the error handling.

**Comment by Rapsssito** [comment]
@Pinwheeler, glad it worked! The documentation may not be clear enough. I will try to fix that as soon as possible.
