### ISSUE TITLE
Execution failed for task ':react-native-tcp-socket:compileDebugJavaWithJavac'

### ISSUE THREAD

**Issue by duartealexf** [Rapsssito/react-native-tcp-socket#4]
Happens when running `react-native run-android`.

Output:

```
[Warning] Target simulator is not supported for Android platform. 
 If you want to use particular device or simulator for launching Android app,
 please specify  device id (as in 'adb devices' output) instead.

[Info] local.properties file doesn't exist. Using Android SDK location from PATH.

[Info] Starting React Native Packager.

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1202 file(s) to forward-jetify. Using 4 workers...
info Installing the app...

> Configure project :app
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed at the end of 2018. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Configure project :react-native-camera-kit
WARNING: The specified Android SDK Build Tools version (26.0.2) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.4.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Configure project :react-native-fs
WARNING: The specified Android SDK Build Tools version (26.0.3) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.4.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.3'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Configure project :rncamerakit
WARNING: The specified Android SDK Build Tools version (26.0.2) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.4.1.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '26.0.2'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :@react-native-community_async-storage:preBuild UP-TO-DATE
> Task :@react-native-community_async-storage:preDebugBuild UP-TO-DATE
> Task :@react-native-community_async-storage:checkDebugManifest
> Task :@react-native-community_async-storage:generateDebugBuildConfig
> Task :@react-native-community_async-storage:generateDebugResValues
> Task :@react-native-community_async-storage:processDebugManifest
> Task :@react-native-community_async-storage:prepareLintJar UP-TO-DATE
> Task :@react-native-community_cameraroll:preBuild UP-TO-DATE
> Task :@react-native-community_cameraroll:preDebugBuild UP-TO-DATE
> Task :@react-native-community_cameraroll:checkDebugManifest
> Task :@react-native-community_cameraroll:generateDebugBuildConfig
> Task :@react-native-community_cameraroll:generateDebugResValues
> Task :@react-native-community_cameraroll:processDebugManifest
> Task :@react-native-community_cameraroll:prepareLintJar UP-TO-DATE
> Task :app:generatePackageList
> Task :app:preBuild
> Task :react-native-camera-kit:preBuild UP-TO-DATE
> Task :react-native-camera-kit:preDebugBuild UP-TO-DATE
> Task :react-native-camera-kit:checkDebugManifest
> Task :react-native-camera-kit:processDebugManifest
> Task :react-native-fs:preBuild UP-TO-DATE
> Task :react-native-fs:preDebugBuild UP-TO-DATE
> Task :react-native-fs:checkDebugManifest
> Task :react-native-fs:processDebugManifest
> Task :react-native-gesture-handler:preBuild UP-TO-DATE
> Task :react-native-gesture-handler:preDebugBuild UP-TO-DATE
> Task :react-native-gesture-handler:checkDebugManifest
> Task :react-native-gesture-handler:processDebugManifest
> Task :react-native-reanimated:preBuild UP-TO-DATE
> Task :react-native-reanimated:preDebugBuild UP-TO-DATE
> Task :react-native-reanimated:checkDebugManifest
> Task :react-native-reanimated:processDebugManifest
> Task :react-native-safe-area-context:preBuild UP-TO-DATE
> Task :react-native-safe-area-context:preDebugBuild UP-TO-DATE
> Task :react-native-safe-area-context:checkDebugManifest
> Task :react-native-safe-area-context:processDebugManifest
> Task :react-native-screens:preBuild UP-TO-DATE
> Task :react-native-screens:preDebugBuild UP-TO-DATE
> Task :react-native-screens:checkDebugManifest
> Task :react-native-screens:processDebugManifest
> Task :react-native-tcp-socket:preBuild UP-TO-DATE
> Task :react-native-tcp-socket:preDebugBuild UP-TO-DATE
> Task :react-native-tcp-socket:checkDebugManifest
> Task :react-native-tcp-socket:processDebugManifest
> Task :react-native-vector-icons:preBuild UP-TO-DATE
> Task :react-native-vector-icons:preDebugBuild UP-TO-DATE
> Task :react-native-vector-icons:checkDebugManifest
> Task :react-native-vector-icons:processDebugManifest
> Task :react-native-wifi-p2p:preBuild UP-TO-DATE
> Task :react-native-wifi-p2p:preDebugBuild UP-TO-DATE
> Task :react-native-wifi-p2p:checkDebugManifest
> Task :react-native-wifi-p2p:processDebugManifest
> Task :rncamerakit:preBuild UP-TO-DATE
> Task :rncamerakit:preDebugBuild UP-TO-DATE
> Task :rncamerakit:checkDebugManifest UP-TO-DATE
> Task :rncamerakit:processDebugManifest
> Task :@react-native-community_async-storage:compileDebugAidl NO-SOURCE
> Task :@react-native-community_async-storage:compileDebugRenderscript NO-SOURCE
> Task :@react-native-community_async-storage:generateDebugResources
> Task :@react-native-community_async-storage:packageDebugResources
> Task :@react-native-community_async-storage:generateDebugRFile
> Task :@react-native-community_async-storage:generateDebugSources
> Task :@react-native-community_async-storage:javaPreCompileDebug
> Task :@react-native-community_async-storage:compileDebugJavaWithJavac
> Task :@react-native-community_async-storage:bundleLibCompileDebug
> Task :@react-native-community_cameraroll:compileDebugAidl NO-SOURCE
> Task :@react-native-community_cameraroll:compileDebugRenderscript NO-SOURCE
> Task :@react-native-community_cameraroll:generateDebugResources
> Task :@react-native-community_cameraroll:packageDebugResources
> Task :@react-native-community_cameraroll:generateDebugRFile
> Task :@react-native-community_cameraroll:generateDebugSources
> Task :@react-native-community_cameraroll:javaPreCompileDebug
> Task :@react-native-community_cameraroll:compileDebugJavaWithJavac
> Task :@react-native-community_cameraroll:bundleLibCompileDebug
> Task :react-native-camera-kit:compileDebugAidl NO-SOURCE
> Task :react-native-gesture-handler:compileDebugAidl NO-SOURCE
> Task :react-native-safe-area-context:compileDebugAidl NO-SOURCE
> Task :react-native-reanimated:compileDebugAidl NO-SOURCE
> Task :react-native-screens:compileDebugAidl NO-SOURCE
> Task :react-native-tcp-socket:compileDebugAidl NO-SOURCE
> Task :react-native-vector-icons:compileDebugAidl NO-SOURCE
> Task :react-native-fs:compileDebugAidl NO-SOURCE
> Task :react-native-wifi-p2p:compileDebugAidl NO-SOURCE
> Task :app:preDebugBuild
> Task :@react-native-community_async-storage:packageDebugRenderscript NO-SOURCE
> Task :rncamerakit:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :@react-native-community_cameraroll:packageDebugRenderscript NO-SOURCE
> Task :react-native-camera-kit:packageDebugRenderscript NO-SOURCE
> Task :react-native-fs:packageDebugRenderscript NO-SOURCE
> Task :react-native-gesture-handler:packageDebugRenderscript NO-SOURCE
> Task :react-native-reanimated:packageDebugRenderscript NO-SOURCE
> Task :react-native-safe-area-context:packageDebugRenderscript NO-SOURCE
> Task :react-native-screens:packageDebugRenderscript NO-SOURCE
> Task :react-native-tcp-socket:packageDebugRenderscript NO-SOURCE
> Task :react-native-vector-icons:packageDebugRenderscript NO-SOURCE
> Task :react-native-wifi-p2p:packageDebugRenderscript NO-SOURCE
> Task :rncamerakit:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript NO-SOURCE
> Task :app:checkDebugManifest
> Task :app:generateDebugBuildConfig
> Task :app:bundleDebugJsAndAssets SKIPPED
> Task :app:prepareLintJar UP-TO-DATE
> Task :app:generateDebugSources
> Task :react-native-camera-kit:compileDebugRenderscript NO-SOURCE
> Task :react-native-camera-kit:generateDebugBuildConfig
> Task :react-native-camera-kit:generateDebugResValues
> Task :react-native-camera-kit:generateDebugResources
> Task :react-native-camera-kit:packageDebugResources
> Task :react-native-camera-kit:generateDebugRFile
> Task :react-native-camera-kit:prepareLintJar UP-TO-DATE
> Task :react-native-camera-kit:generateDebugSources
> Task :react-native-fs:compileDebugRenderscript NO-SOURCE
> Task :react-native-fs:generateDebugBuildConfig
> Task :react-native-fs:generateDebugResValues
> Task :react-native-fs:generateDebugResources
> Task :react-native-fs:packageDebugResources
> Task :react-native-fs:generateDebugRFile
> Task :react-native-fs:prepareLintJar UP-TO-DATE
> Task :react-native-fs:generateDebugSources
> Task :react-native-fs:javaPreCompileDebug

> Task :react-native-fs:compileDebugJavaWithJavac

> Task :react-native-fs:bundleLibCompileDebug
> Task :react-native-gesture-handler:compileDebugRenderscript NO-SOURCE
> Task :react-native-gesture-handler:generateDebugBuildConfig
> Task :react-native-gesture-handler:generateDebugResValues
> Task :react-native-gesture-handler:generateDebugResources
> Task :react-native-gesture-handler:packageDebugResources
> Task :react-native-gesture-handler:generateDebugRFile
> Task :react-native-gesture-handler:prepareLintJar UP-TO-DATE
> Task :react-native-gesture-handler:generateDebugSources
> Task :react-native-gesture-handler:javaPreCompileDebug

> Task :react-native-gesture-handler:compileDebugJavaWithJavac

> Task :react-native-gesture-handler:bundleLibCompileDebug
> Task :react-native-camera-kit:javaPreCompileDebug

> Task :react-native-camera-kit:compileDebugJavaWithJavac

> Task :react-native-camera-kit:bundleLibCompileDebug
> Task :react-native-reanimated:generateDebugBuildConfig
> Task :react-native-reanimated:compileDebugRenderscript NO-SOURCE
> Task :react-native-reanimated:generateDebugResValues
> Task :react-native-reanimated:generateDebugResources
> Task :react-native-reanimated:packageDebugResources
> Task :react-native-reanimated:generateDebugRFile
> Task :react-native-reanimated:prepareLintJar UP-TO-DATE
> Task :react-native-reanimated:generateDebugSources
> Task :react-native-reanimated:javaPreCompileDebug

> Task :react-native-reanimated:compileDebugJavaWithJavac

> Task :react-native-reanimated:bundleLibCompileDebug
> Task :react-native-safe-area-context:generateDebugBuildConfig
> Task :react-native-safe-area-context:compileDebugRenderscript NO-SOURCE
> Task :react-native-safe-area-context:generateDebugResValues
> Task :react-native-safe-area-context:generateDebugResources
> Task :react-native-safe-area-context:packageDebugResources
> Task :react-native-safe-area-context:generateDebugRFile
> Task :react-native-safe-area-context:prepareLintJar UP-TO-DATE
> Task :react-native-safe-area-context:generateDebugSources
> Task :react-native-safe-area-context:javaPreCompileDebug
> Task :react-native-safe-area-context:compileDebugJavaWithJavac
> Task :react-native-safe-area-context:bundleLibCompileDebug
> Task :react-native-screens:generateDebugBuildConfig
> Task :react-native-screens:compileDebugRenderscript NO-SOURCE
> Task :react-native-screens:generateDebugResValues
> Task :react-native-screens:generateDebugResources
> Task :react-native-screens:prepareLintJar UP-TO-DATE
> Task :react-native-screens:packageDebugResources
> Task :react-native-screens:generateDebugRFile
> Task :react-native-screens:generateDebugSources
> Task :react-native-screens:javaPreCompileDebug
> Task :react-native-screens:compileDebugJavaWithJavac
> Task :react-native-screens:bundleLibCompileDebug
> Task :react-native-tcp-socket:compileDebugRenderscript NO-SOURCE
> Task :react-native-tcp-socket:generateDebugBuildConfig
> Task :react-native-tcp-socket:generateDebugResValues
> Task :react-native-tcp-socket:generateDebugResources
> Task :react-native-tcp-socket:packageDebugResources
> Task :react-native-tcp-socket:generateDebugRFile
> Task :react-native-tcp-socket:prepareLintJar UP-TO-DATE
> Task :react-native-tcp-socket:generateDebugSources
> Task :react-native-tcp-socket:javaPreCompileDebug

> Task :react-native-tcp-socket:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings
100 actionable tasks: 89 executed, 11 up-to-date
Note: /Users/alexandre/Projects/socket/node_modules/react-native-fs/android/src/main/java/com/rnfs/RNFSManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/alexandre/Projects/socket/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/alexandre/Projects/socket/node_modules/react-native-camera-kit/android/src/main/java/com/wix/RNCameraKit/gallery/GalleryViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/alexandre/Projects/socket/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
/Users/alexandre/Projects/socket/node_modules/react-native-tcp-socket/android/src/main/java/com/asterinet/react/tcpsocket/TcpSocketModule.java:58: error: cannot find symbol
        new GuardedAsyncTask<Void, Void>(getReactApplicationContext().getExceptionHandler()) {
                                                                     ^
  symbol:   method getExceptionHandler()
  location: class ReactApplicationContext
/Users/alexandre/Projects/socket/node_modules/react-native-tcp-socket/android/src/main/java/com/asterinet/react/tcpsocket/TcpSocketModule.java:90: error: cannot find symbol
        new GuardedAsyncTask<Void, Void>(getReactApplicationContext().getExceptionHandler()) {
                                                                     ^
  symbol:   method getExceptionHandler()
  location: class ReactApplicationContext
/Users/alexandre/Projects/socket/node_modules/react-native-tcp-socket/android/src/main/java/com/asterinet/react/tcpsocket/TcpSocketModule.java:115: error: cannot find symbol
        new GuardedAsyncTask<Void, Void>(getReactApplicationContext().getExceptionHandler()) {
                                                                     ^
  symbol:   method getExceptionHandler()
  location: class ReactApplicationContext
/Users/alexandre/Projects/socket/node_modules/react-native-tcp-socket/android/src/main/java/com/asterinet/react/tcpsocket/TcpSocketModule.java:141: error: cannot find symbol
        new GuardedAsyncTask<Void, Void>(getReactApplicationContext().getExceptionHandler()) {
                                                                     ^
  symbol:   method getExceptionHandler()
  location: class ReactApplicationContext
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-tcp-socket:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 51s

error Failed to install the app. Make sure you have the Android development environment set up: https://facebook.github.io/react-native/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: ./gradlew app:installDebug -PreactNativeDevServerPort=8081
Note: /Users/alexandre/Projects/socket/node_modules/react-native-fs/android/src/main/java/com/rnfs/RNFSManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/alexandre/Projects/socket/node_modules/react-native-gesture-handler/android/src/main/java/com/swmansion/gesturehandler/react/RNGestureHandlerButtonViewManager.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: /Users/alexandre/Projects/socket/node_modules/react-native-camera-kit/android/src/main/java/com/wix/RNCameraKit/gallery/GalleryViewManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
Note: /Users/alexandre/Projects/socket/node_modules/react-native-reanimated/android/src/main/java/com/swmansion/reanimated/NodesManager.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
/Users/alexandre/Projects/socket/node_modules/react-native-tcp-socket/android/src/main/java/com/asterinet/react/tcpsocket/TcpSocketModule.java:58: error: cannot find symbol
        new GuardedAsyncTask<Void, Void>(getReactApplicationContext().getExceptionHandler()) {
                                                                     ^
  symbol:   method getExceptionHandler()
  location: class ReactApplicationContext
/Users/alexandre/Projects/socket/node_modules/react-native-tcp-socket/android/src/main/java/com/asterinet/react/tcpsocket/TcpSocketModule.java:90: error: cannot find symbol
        new GuardedAsyncTask<Void, Void>(getReactApplicationContext().getExceptionHandler()) {
                                                                     ^
  symbol:   method getExceptionHandler()
  location: class ReactApplicationContext
/Users/alexandre/Projects/socket/node_modules/react-native-tcp-socket/android/src/main/java/com/asterinet/react/tcpsocket/TcpSocketModule.java:115: error: cannot find symbol
        new GuardedAsyncTask<Void, Void>(getReactApplicationContext().getExceptionHandler()) {
                                                                     ^
  symbol:   method getExceptionHandler()
  location: class ReactApplicationContext
/Users/alexandre/Projects/socket/node_modules/react-native-tcp-socket/android/src/main/java/com/asterinet/react/tcpsocket/TcpSocketModule.java:141: error: cannot find symbol
        new GuardedAsyncTask<Void, Void>(getReactApplicationContext().getExceptionHandler()) {
                                                                     ^
  symbol:   method getExceptionHandler()
  location: class ReactApplicationContext
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
4 errors

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-tcp-socket:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2m 51s

    at checkExecSyncError (child_process.js:629:11)
    at execFileSync (child_process.js:647:13)
    at runOnAllDevices (/Users/alexandre/Projects/socket/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/runOnAllDevices.js:74:39)
    at buildAndRun (/Users/alexandre/Projects/socket/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:158:41)
    at Object.runAndroid [as func] (/Users/alexandre/Projects/socket/node_modules/@react-native-community/cli-platform-android/build/commands/runAndroid/index.js:106:12)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I followed all steps from this project's README file.

`build.gradle`: 

```// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "28.0.3"
        minSdkVersion = 23
        compileSdkVersion = 28
        targetSdkVersion = 28
        supportLibVersion = "28.0.0"
    }
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath("com.android.tools.build:gradle:3.4.1")

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        mavenLocal()
        maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url("$rootDir/../node_modules/react-native/android")
        }
        maven {
            // Android JSC is installed from npm
            url("$rootDir/../node_modules/jsc-android/dist")
        }

        google()
        jcenter()
    }
}
```

**Comment by duartealexf** [comment]
my package.json:

```
{
  "name": "socket",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint .",
    "run-dev": "yarn cache clean && react-native run-android && react-native log-android",
    "build-dev": "react-native bundle --dev false --platform android --entry-file index.js --bundle-output ./android/app/src/main/assets/index.android.bundle --assets-dest ./android/app/src/main/res && cd android && ./gradlew assembleDebug",
    "clean": "cd android && ./gradlew clean && rm -rf ~/.gradle/caches/*"
  },
  "dependencies": {
    "@react-native-community/async-storage": "^1.6.2",
    "@react-native-community/cameraroll": "^1.2.1",
    "@react-native-community/cli": "^2.9.0",
    "axios": "^0.19.0",
    "color": "^3.1.2",
    "formik": "^1.5.8",
    "lodash": "^4.17.15",
    "moment": "^2.24.0",
    "prop-types": "^15.7.2",
    "qs": "^6.9.0",
    "react": "16.8.6",
    "react-dom": "^16.8.6",
    "react-native": "0.60.0",
    "react-native-camera-kit": "^8.0.2",
    "react-native-circular-action-menu-hero99": "^0.5.0",
    "react-native-easy-grid": "^0.2.2",
    "react-native-fs": "^2.15.2",
    "react-native-gesture-handler": "^1.4.1",
    "react-native-image-mapper": "^0.1.11",
    "react-native-masked-text": "^1.13.0",
    "react-native-modal-datetime-picker": "^7.6.0",
    "react-native-paper": "^2.16.0",
    "react-native-reanimated": "^1.3.0",
    "react-native-safe-area-context": "^0.5.0",
    "react-native-screens": "^1.0.0-alpha.23",
    "react-native-tcp-socket": "^1.2.1",
    "react-native-vector-icons": "^6.6.0",
    "react-native-wifi-p2p": "^1.0.0",
    "react-navigation": "^4.0.10",
    "react-navigation-stack": "^1.10.2",
    "react-redux": "^7.1.1",
    "redux": "^4.0.4",
    "redux-thunk": "^2.3.0",
    "yup": "^0.27.0"
  },
  "devDependencies": {
    "@babel/core": "^7.6.4",
    "@babel/runtime": "^7.6.3",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "eslint-config-prettier": "^6.4.0",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.8.6"
  },
  "jest": {
    "preset": "react-native"
  }
}
```

**Comment by Rapsssito** [comment]
Thanks for the report. Working on a solution.

**Comment by Rapsssito** [comment]
The issue is related to your RN version. The library uses methods only available in RN >= 0.61.

I have released **`1.2.2`**, compatible with RN 0.60. Check if everything works. Refer to the [README](https://github.com/Rapsssito/react-native-tcp-socket#react-native-compatibility) for more details.

**Comment by duartealexf** [comment]
Thank you so much! I will try it out and let you know!

**Comment by duartealexf** [comment]
Great! It worked! You're the best! Cheers!
