### ISSUE TITLE
react-native-tcp:compileDebugJavaWithJavac FAILED

### ISSUE THREAD

**Issue by diegoaraujolima** [Rapsssito/react-native-tcp-socket#43]
Hi. On execute npm run android:
```
> FinalPointTKD@0.0.1 android C:\Users\diego\Documents\Startei - Git\FinalPointTKD\mobile
> react-native run-android

info Running jetifier to migrate libraries to AndroidX. You can disable it using "--no-jetifier" flag.
Jetifier found 1586 file(s) to forward-jetify. Using 4 workers...
info JS server already running.
info Installing the app...

> Configure project :react-native-orientation
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed soon. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Configure project :react-native-os
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed soon. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Configure project :react-native-tcp
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed soon. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html

> Configure project :react-native-udp
WARNING: Configuration 'compile' is obsolete and has been replaced with 'implementation' and 'api'.
It will be removed soon. For more information see: http://d.android.com/r/tools/update-dependency-configurations.html
WARNING: The specified Android SDK Build Tools version (23.0.1) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.5.2.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '23.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
WARNING: The specified Android SDK Build Tools version (23.0.1) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.5.2.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '23.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.
WARNING: The specified Android SDK Build Tools version (23.0.1) is ignored, as it is below the minimum supported version (28.0.3) for Android Gradle Plugin 3.5.2.
Android SDK Build Tools 28.0.3 will be used.
To suppress this warning, remove "buildToolsVersion '23.0.1'" from your build.gradle file, as each version of the Android Gradle Plugin now has a default version of the build tools.

> Task :react-native-tcp:compileDebugJavaWithJavac FAILED

Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/6.0.1/userguide/command_line_interface.html#sec:command_line_warnings
92 actionable tasks: 2 executed, 90 up-to-date

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-tcp:compileDebugJavaWithJavac'.
> java.io.IOException: Unable to delete directory 'C:\Users\diego\Documents\Startei - Git\FinalPointTKD\mobile\node_modules\react-native-tcp\android\build\intermediates\javac\debug\classes'
    Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
    - C:\Users\diego\Documents\Startei - Git\FinalPointTKD\mobile\node_modules\react-native-tcp\android\build\intermediates\javac\debug\classes\com

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/getting-started.html#android-development-environment. Run CLI with --verbose flag for more details.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-tcp:compileDebugJavaWithJavac'.
> java.io.IOException: Unable to delete directory 'C:\Users\diego\Documents\Startei - Git\FinalPointTKD\mobile\node_modules\react-native-tcp\android\build\intermediates\javac\debug\classes'
    Failed to delete some children. This might happen because a process has files open or has its working directory set in the target directory.
    - C:\Users\diego\Documents\Startei - Git\FinalPointTKD\mobile\node_modules\react-native-tcp\android\build\intermediates\javac\debug\classes\com

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 14s

    at makeError (C:\Users\diego\Documents\Startei - Git\FinalPointTKD\mobile\node_modules\execa\index.js:174:9)
    at C:\Users\diego\Documents\Startei - Git\FinalPointTKD\mobile\node_modules\execa\index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async runOnAllDevices (C:\Users\diego\Documents\Startei - Git\FinalPointTKD\mobile\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:94:5)
    at async Command.handleAction (C:\Users\diego\Documents\Startei - Git\FinalPointTKD\mobile\node_modules\react-native\node_modules\@react-native-community\cli\build\index.js:186:9)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! FinalPointTKD@0.0.1 android: `react-native run-android`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the FinalPointTKD@0.0.1 android script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\diego\AppData\Roaming\npm-cache\_logs\2020-04-22T01_25_21_932Z-debug.log
```

Can help me?

**Comment by Rapsssito** [comment]
@diegoaraujolima, thanks for your feedback! It looks like you might have some permission issues, try to run `cd android` and then `./gradlew clean`.

**Comment by whitetiger1002** [comment]
I got this issue on my side. I tried to run 'gradlew clean', but it's same.
Could anyone help me?

**Comment by Rapsssito** [comment]
@whitetiger1002, could you open a new issue with the error stack trace so I can take a deeper look at your problem?

**Comment by RahulKumar-JPLoft** [comment]
I am getting the same issue, can anyone help, how I can resolve this...


FAILURE: Build completed with 2 failures.

1: Task failed with an exception.
-----------
* What went wrong:
Execution failed for task ':react-native-tcp:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
java.lang.StackOverflowError (no error message)

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 45s

    at makeError (D:\ReactNative\Proof\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:174:9)
    at D:\ReactNative\Proof\node_modules\@react-native-community\cli-platform-android\node_modules\execa\index.js:278:16
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async runOnAllDevices (D:\ReactNative\Proof\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (D:\ReactNative\Proof\node_modules\@react-native-community\cli\build\index.js:142:9)
info Run CLI with --verbose flag for more details.
