### ISSUE TITLE
RejectedExecutionException: AsyncTask.THREAD_POOL_EXECUTOR overflowing

### ISSUE THREAD

**Issue by lubbo** [Rapsssito/react-native-tcp-socket#45]
## Description
I'm trying to implement a device detection.
To detect a device in the network I'm opening a socket and connecting to every IP address in the network: if the connection succeeds, then the device is detected.
To accomplish that I'm cycling through all IPs and I invoke a function that create a connection to the specific host.

In iOS works fine, but in Android after some sockets are opened, this failure is raised:

```
2020-05-06 11:07:58.476 31379-31473/com.awesomeproject E/unknown:ReactNative: Exception in native call
    java.util.concurrent.RejectedExecutionException: Task android.os.AsyncTask$3@abd3dfc rejected from java.util.concurrent.ThreadPoolExecutor@85e5c85[Running, pool size = 17, active threads = 17, queued tasks = 128, completed tasks = 59]
        at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2078)
        at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:843)
        at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1389)
        at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:651)
        at com.asterinet.react.tcpsocket.TcpSocketModule.end(TcpSocketModule.java:135)
        at com.asterinet.react.tcpsocket.TcpSocketModule.destroy(TcpSocketModule.java:141)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:789)
        at android.os.Handler.dispatchMessage(Handler.java:98)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:164)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
        at java.lang.Thread.run(Thread.java:764)
```

## Steps to reproduce

```
for(i=0;i<ips.length;i++){
   ip = ips[i]
   port = 9600
   scanHost(ip,port).then((result) => {...}).catch((result) => {...})
}

// Function to scan hosts
const scanHost = (hostIP, hostPort) => {
    return new Promise(function (resolve, reject) {
        const client = TcpSocket.createConnection(
            {
                host: hostIP,
                port: hostPort
            }
        )

        client.on('connect', function () {
            client.end('finished')
        })

        client.on('end', function (data) {
            var scan_result = {
                success: true,
                ip: hostIP,
                port: hostPort
            }
            resolve(scan_result)
        })

       
        client.on('error', function (err) {
            var scan_result = {
                success: false,
                ip: hostIP,
                port: hostPort,
                error: err
            }
            client.destroy()
            reject(scan_result)
        })

        setTimeout(function () {

            var scan_result = {
                success: false,
                ip: hostIP,
                port: hostPort,
                error: 'Timeout (external)'
            }
            client.destroy()
            reject(scan_result)
        }, 4000)
    })
}
```

## Relevant information
|             |     |
| ----------- | --- |
| OS | Android 8.0.0 Samsung SM-A530F   |
| react-native | 0.62.0   |
| react-native-tcp-socket  | 3.5.0  |

**Comment by Rapsssito** [comment]
@lubbo, thanks for the feedback! It looks like the thread pool is overflowing with requests. I will take a look and reply ASAP.

**Comment by Rapsssito** [comment]
@lubbo, I found the issue. It is related to `AsyncTask.THREAD_POOL_EXECUTOR` being overwhelmed with parallel tasks (the limit is 128). Since `AsyncTask` is going to be deprecated in Android R, to fix this issue **I will have to refactor some of the Android code**.

In the meantime, a workaround would be to schedule your `for` to do 100 queries at a time, then wait for them to finish (so the `THREAD_POOL_EXECUTOR` is free) and continue with another 100 queries.
